  import { ArrowUpRight } from "lucide-react";
  import Image from "next/image";

  const BlogHeader = ({ title }) => (
    <h1 className="text-left font-bold text-4xl">{title}</h1>
  );

  const BlogParagraph = ({ children }) => (
    <p className="leading-7 text-neutral-300 text-lg">{children}</p>
  );

  const BlogImage = ({ src, alt }) => (
    <Image
      src={src}
      alt={alt}
      width={500}
      height={500}
      className="w-full brightness-75 border-2 border-white rounded-lg"
      priority
    />
  );

  const Page = () => (
    <section className="flex flex-col items-center gap-10 p-10 w-full">
      <div className="max-w-3xl mt-10 flex flex-col gap-5">
        <BlogHeader title="How I built naminggenie.com" />
        <BlogParagraph>
          This website provides domain names that are available for registration,
          generated from your business description using a large language model.
        </BlogParagraph>
      </div>
      <div className="max-w-lg w-full">
        <BlogImage src="/naminggenie.webp" alt="NamingGenie website" />
      </div>
      <div className="max-w-3xl mt-5 flex flex-col gap-5">
        <BlogParagraph>
          This project taught me a great deal. It started as an HTML, CSS, and
          JavaScript project and evolved into a full-stack Next.js project.
          Screenshots of each iteration are below.
        </BlogParagraph>
        <BlogParagraph>
          Initially, it was a simple static one-page site. A friend assisted in
          setting up a backend Express server to interact with the API.
        </BlogParagraph>
      </div>
      <div className="max-w-lg w-full">
        <BlogImage src="/dominator.webp" alt="First version of NamingGenie" />
      </div>
      <div className="max-w-3xl mt-3 flex flex-col gap-5">
        <BlogParagraph>
          The first working version of the site was built using only HTML and CSS
          with a Node.js Express server. We got our affiliate form approved from
          namecheap.com, earning 20% per order.
        </BlogParagraph>
      </div>
      <div className="max-w-lg w-full">
        <BlogImage src="/naming.webp" alt="Second version of NamingGenie" />
      </div>
      <div className="max-w-3xl mt-3 flex flex-col gap-5">
        <BlogParagraph>
          The second iteration brought design modifications and finalized the
          domain "naminggenie.com," which was generated by our app.
        </BlogParagraph>
      </div>
      <div className="max-w-lg w-full space-y-5">
        <Image
          src={"/three-blog (3).webp"}
          alt={"third version"}
          width={1000}
          height={1000}
          className="w-full brightness-75 border-2 border-white rounded-lg"
          priority
        />
      </div>
      <div className="max-w-3xl mt-3 flex flex-col gap-5">
        <BlogParagraph>
          The third iteration brought significant design and code modifications,
          though it was still not running on any framework. During this phase, I
          learned a great deal about backend Express development as I built a
          complete blogging system. We realized that the most effective organic
          way to drive traffic was through SEO. Below, you'll see the blog
          template i developed.
        </BlogParagraph>
      </div>
      <div className="max-w-lg w-full space-y-5">
        <Image
          src={"/three-blog (1).webp"}
          alt={"third version"}
          width={1000}
          height={1000}
          className="w-full brightness-75 border-2 border-white rounded-lg"
          priority
        />
      </div>
      <div className="max-w-3xl mt-3 flex flex-col gap-5">
        <BlogParagraph>
          My co-founder was inchage the of seo while he learnt all about seo and started writing blogs i learnt react, tailwindcss, nextjs, prisma, zustand and more. nad created the fourth itiration of the website.
        </BlogParagraph>
      </div>
      <div className="max-w-lg w-full">
        <BlogImage src="/naminggenie.webp" alt="NamingGenie website" />
      </div>
      <div className="max-w-3xl mt-3 flex flex-col gap-5">
        <BlogParagraph>
          This is the version which is up abd running currently, this uses nextjs and has about 50 page of blogs wrttien for seo. you can check it out here <a target="_blank" href="https://www.naminggenie.com/" className="inline-flex cursor-pointer underline gap-1 items-center">naminggenie.com <ArrowUpRight/></a>
        </BlogParagraph>
      </div>
    </section>
  );

  export default Page;
